Removes comma after json message
Caused exception:
net.sf.json.JSONException: Found starting '{' but missing '}' at the end. at character 0 of null

Signed-off-by: Aske Olsson <aske.olsson@switch-gears.dk>